# Generated by Django 5.0.14 on 2026-01-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyWorkload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("staff_id", models.PositiveIntegerField()),
                ("week_start", models.DateField()),
                ("total_hours", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "weekly_workload",
                "unique_together": {("staff_id", "week_start")},
            },
        ),
    ]
